<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Keypaste.App.Tests</RootNamespace>
    <AssemblyName>Keypaste.App.Tests</AssemblyName>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Avalonia.Headless" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Keypaste.App/Keypaste.App.csproj" />
  </ItemGroup>

</Project>
