using System.Runtime.InteropServices;

namespace Keypaste.Cli.Execution;

/// <summary>Decides which signals keypaste has to relay to the child itself.</summary>
/// <remarks>
/// Pure and separate from the code that spawns anything, because it is the one judgement call in
/// signal handling and it should be assertable without a process.
/// </remarks>
internal static class SignalPolicy
{
    /// <summary>Whether <paramref name="signal"/> must be delivered to the child by keypaste.</summary>
    /// <param name="signal">The signal keypaste received.</param>
    /// <param name="stdinRedirected">
    /// Whether keypaste's stdin is not a terminal, sampled once before the child starts. A proxy
    /// for "nothing here is attached to a tty", which is exact enough and costs no syscall in a
    /// handler that must not block.
    /// </param>
    /// <remarks>
    /// <para>
    /// SIGINT, SIGQUIT and SIGHUP are generated by the terminal driver and delivered to the whole
    /// foreground process group, which the child is already in. Relaying them there would deliver
    /// each one twice — and a second Ctrl+C means "stop being graceful" to docker compose, to npm,
    /// and to most servers. So when there is a terminal, keypaste's only job is to stay alive long
    /// enough to reap the child and report its status.
    /// </para>
    /// <para>
    /// When there is no terminal — CI, systemd, a container where keypaste is PID 1 — nothing
    /// delivered them and keypaste must. SIGTERM is never terminal-generated, so it is always
    /// keypaste's to relay: <c>docker stop</c> and <c>timeout</c> both send it to keypaste alone,
    /// and without the relay they would kill the wrapper and orphan the child.
    /// </para>
    /// </remarks>
    internal static bool ShouldForward(PosixSignal signal, bool stdinRedirected) =>
        signal == PosixSignal.SIGTERM || stdinRedirected;
}
